# Generated by Django 4.2.3 on 2023-11-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, verbose_name='Логин')),
                ('science', models.CharField(max_length=100, verbose_name='Наука')),
                ('kriminal', models.CharField(max_length=100, verbose_name='Криминал')),
                ('comedy', models.CharField(max_length=100, verbose_name='Комедии')),
                ('horror', models.CharField(max_length=100, verbose_name='Ужасы')),
                ('multfilm', models.CharField(max_length=100, verbose_name='Мультфильмы')),
                ('dram', models.CharField(max_length=100, verbose_name='Фантастика')),
                ('fantazy', models.CharField(max_length=100, verbose_name='Драммы')),
                ('serial', models.CharField(max_length=100, verbose_name='Сериалы')),
                ('film', models.CharField(max_length=100, verbose_name='Фильмы')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистики',
            },
        ),
    ]
