# Generated by Django 4.2.3 on 2023-10-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('image', models.CharField(max_length=200, verbose_name='Logo')),
                ('description', models.CharField(max_length=300, verbose_name='описание')),
                ('release_date', models.CharField(max_length=30, verbose_name='Дата выхода')),
                ('review', models.CharField(max_length=300, verbose_name='Обзор')),
                ('countseason', models.CharField(max_length=10, verbose_name='Количество сезонов')),
                ('view', models.CharField(max_length=100, verbose_name='Фильм или Сериал')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
