# Generated by Django 4.2.3 on 2023-10-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialname', models.CharField(max_length=50, verbose_name='Название сериала')),
                ('linkseries', models.CharField(max_length=300, verbose_name='Ссылка на серию')),
                ('numberseason', models.CharField(max_length=50, verbose_name='Номер сезона')),
                ('prevewimage', models.CharField(max_length=300, verbose_name='Превью серии')),
                ('numberseries', models.CharField(max_length=20, verbose_name='Номер серии')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
            },
        ),
    ]
