# Generated by Django 4.2.3 on 2023-10-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_season1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginCom', models.CharField(max_length=50, verbose_name='Логин пользователя')),
                ('serialName', models.CharField(max_length=50, verbose_name='Название сериала')),
                ('text', models.TextField(max_length=300, verbose_name='Текст комментария')),
                ('like', models.CharField(max_length=10, verbose_name='Лайки')),
                ('dislike', models.CharField(max_length=10, verbose_name='Дизлайки')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
